### ISSUE TITLE
The colab launches the webui from the wrong folder

### ISSUE THREAD

**Issue by pinilpypinilpy** [hlky/stable-diffusion#108]
In the colab, the final launch command is: 
`!python /content/stable-diffusion/scripts/webui.py \
--ckpt '{models_path}/sd-v1-4.ckpt' \
--outdir '{output_path}' \
--share {vars}`

Which throws an error because webui.py tries to find optimizedSD/v1-inference.yaml in the /content directory.

An easy solution is:
`%cd  /content/stable-diffusion
!python scripts/webui.py \
--ckpt '{models_path}/sd-v1-4.ckpt' \
--outdir '{output_path}' \
--share {vars}`

**Comment by hlky** [comment]
@altryne

**Comment by altryne** [comment]
Yeah I saw this, it's what I get by... linking directly to a repo instead of pining a version! 
@hlky are we going to do released at some point ? 😂

@pinilpypinilpy this was fixed in https://github.com/altryne/sd-webui-colab/commit/d0ac994d065722c8a07742865bc0b3f0cfb4d89f 
If you don't mind testing again? 🙏 
Thank you for the issue

**Comment by altryne** [comment]
@hlky this can be closed

**Comment by pinilpypinilpy** [comment]
Looks good, thanks!

As an aside, would it be possible to have the notebook download the model for people with slow upload speeds?

I ended up using this: https://gist.github.com/davo/4b374f41be657f59bfb60d1ee61d2616 to save myself a lot of time

**Comment by alexserpico** [comment]
form me it's working only changing as suggested by @pinilpypinilpy

**Comment by pinilpypinilpy** [comment]
> form me it's working only changing as suggested by @pinilpypinilpy

Yeah I just tested it, the issue seems to be that the !python command isn't on a newline, so it conflict with cd.

**Comment by altryne** [comment]
> 

ugh! that's what I get by doing this in  github 😮‍💨
