### ISSUE TITLE
Unable to pass parameters to webui.cmd

### ISSUE THREAD

**Issue by r-farrell** [hlky/stable-diffusion#109]
If I pass parameters to webui.cmd they seem to be ignored.

Examples I've been trying to use are:

```
./webui.cmd --share
./webui.cmd --share-password
```

The webui.cmd script still runs but the additional parameters don't appear to be passed on and are ignored.

**Comment by lozenge** [comment]
You configure command line arguments by [editing the `scripts/relauncher.py` file](https://github.com/hlky/stable-diffusion-webui/wiki/Command-line-options#setting-command-line-options).

**Comment by hlky** [comment]
The share option is broken due to using Gradio Blocks, it's a known Gradio bug. You will have to use a workaround for internet based remote access.
If you just want to access from another computer at home it's open on all interfaces so just access it with the computer's ip and the port

**Comment by altryne** [comment]
> The share option is br
It's been fixed, if someone adds share, we don't queue and it works both locally and in colab

**Comment by altryne** [comment]
Closing as params can be passed to the relauncher.py script
