### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by ChrisAcrobat** [hlky/stable-diffusion#111]
I tried to push an update my self, but got a Read only response.
I tried to change from:
> Windows Setup (WIP)
> -------
> * Follow the guide to install [Docker Desktop WSL 2 backend](https://docs.docker.com/desktop/windows/wsl/)
> * Verify gpu support by opening WSL and running `nvidia-smi` in the command line
> 
> **Make sure that your git is not converted newlines into Windows format differently from the repository**
> ```
> git config --global core.autocrlf input
> ```
> 
> Please comment if you got everything running successfully and any special steps needed. 

To:
> Windows Setup (WIP*)
> -------
> * Follow the guide to install [Docker Desktop WSL 2 backend](https://docs.docker.com/desktop/windows/wsl/)
> * Verify gpu support by opening WSL and running `nvidia-smi` in the command line
> 
> **Make sure that your git is not converted newlines into Windows format differently from the repository**
> ```
> git config core.autocrlf false
> git reset --hard HEAD
> ```
> 
> \* Please comment if you got everything running successfully and any special steps needed.

With comment:
```
* Changed `git config --global` to local.
* Highlighted the WIP comment.
```

**Comment by hlky** [comment]
The wiki should be editable now if you'd like to do it or I can add this, thanks

**Comment by ChrisAcrobat** [comment]
I'll add it! Give me a few minutes.

**Comment by ChrisAcrobat** [comment]
Done.
