### ISSUE TITLE
Tensor needs to be moved from one gpu to the other.

### ISSUE THREAD

**Issue by ainub** [hlky/stable-diffusion#114]
Great feature to be able to run esrgan and gfpgan on another GPU, however, tensor needs to be moved:
`Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument weight in method wrapper__cudnn_convolution)`

**Comment by hlky** [comment]
When is this happening? Are you using gfpgan/esrgan as an option on generation, or in their standalone tabs?

`gpu 1` is the card you're using for gfpgan/esrgan and `gpu 0` is the card for the main model, correct? 

Have you tried explicitly setting `--gpu` option as well as the other options? there might be something messed up with how the selected gpus are applied

**Comment by ainub** [comment]
Traceback led me to a `facexlib` problem.
Someone else also mentioned it here: [https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/4#issuecomment-1231927656](url)

I guess the only way would be to manually patch `facexlib` or move GFPGAN to cpu only in case you don't want it on GPU.

**Comment by ainub** [comment]
Ok, fixed this way:

`conda activate ldm`
`pip uninstall facexlib`
`git clone https://github.com/xinntao/facexlib`
`cd facexlib`
`git pull origin pull/19/head`
`python setup.py install`
`cd ..`
`python scripts/webui.py --optimized-turbo --gpu 0 --extra-models-gpu --esrgan-gpu 1 --gfpgan-gpu 1`

And everything is working as intended.

**Comment by hlky** [comment]
I've forked, merged that pull request into the fork, and updated the environment.yaml so should be fixed for all now, thanks!
