### ISSUE TITLE
mask mode selection toggle not showing up when mask mode is selected

### ISSUE THREAD

**Issue by mm10ws** [hlky/stable-diffusion#120]
The selection toggle that allows the user to select between "keep masked area" and "regenerate only masked area" no longer shows up in the UI when "Image editor mode" is set to "mask". 

Took a quick look at the code and it looks like it was introduced in commit c0c2a7c0d55561cfb6f42a3681346b9b70749ff1.
Looks like a parameter was removed from the img2img_image_editor_mode.change call in frontend.py but the corresponding value in change_image_editor_mode (ui_functions.py) was not removed. 

I didn't look further to see if there were any other areas that are affected, but when I make the change locally, it brought back the selection toggle.

Edit: Looks Like PR #118 has a fix for this already as part of the work that was done

**Comment by altryne** [comment]
Looks like it's going to be fixed with #118 and if not we'll introduce a fix for that separately.
