### ISSUE TITLE
Masking Issues

### ISSUE THREAD

**Issue by heartlocket** [hlky/stable-diffusion#123]
Finally I have updated but it looks like the same problems I opened an issue about before remain. Foremost, the cursor is offset from the 'mask cursor' palette circle that you paint with. I am not sure why this happens and sometimes resizing the window will fix it a bit but the cursor is often still trailing behind the mask palette. 

Also, why is there no slider to adjust palette size for mask? This is an essential efficiency feature that should come before the more experimental upgrades. It simply makes the masking process too tedious to be working with a tiny pixel brush. This would make the workflow for masking images much smoother.

**Comment by raldnor** [comment]
Perhaps I missed it, but an invert-mask option would be really useful as well.

**Comment by hlky** [comment]
Use photoshop, it is not designed to be a replacement for photoshop. You will get better results doing the masking yourself.

Honestly it's getting a bit ridiculous the amount of complaints about this.  The editor is literally as good as it can be given the technical limitations of gradio, people are expecting too much from a convenience feature.
