### ISSUE TITLE
img2img_k.py - variable typo: Line 282: x_samples should be: x_samples_ddim

### ISSUE THREAD

**Issue by Tollanador** [hlky/stable-diffusion#124]
Simple typo in img2img_k.py as per below.
line 282:     x_samples     should be:    x_samples_ddim

                        samples_ddim = K.sampling.sample_lms(model_wrap_cfg, xi, sigma_sched, extra_args=extra_args, disable=not accelerator.is_main_process)
                        x_samples_ddim = model.decode_first_stage(samples_ddim)
                        x_samples_ddim = torch.clamp((x_samples_ddim + 1.0) / 2.0, min=0.0, max=1.0)
                        x_samples_ddim = accelerator.gather(x_samples_ddim)

                        if accelerator.is_main_process and not opt.skip_save:
                            for x_sample in x_samples:
                                x_sample = 255. * rearrange(x_sample.cpu().numpy(), 'c h w -> h w c')
                                Image.fromarray(x_sample.astype(np.uint8)).save(
                                    os.path.join(sample_path, f"{base_count:05}.png"))
                                base_count += 1
                                
                        if accelerator.is_main_process and not opt.skip_grid:
                            all_samples.append(x_samples_ddim)

![image](https://user-images.githubusercontent.com/45375315/187361731-b91e1e03-16d9-424d-b9a6-e756f4218f8d.png)

**Comment by hlky** [comment]
Legacy script, unsupported. I don't know why you are trying to use that.
