### ISSUE TITLE
Dockerfile Missing pynvml

### ISSUE THREAD

**Issue by bluedevil678** [hlky/stable-diffusion#126]
I had to include this in the latest docker file: 

RUN pip install pynvml

This was required to allow for launch (30/08/22) - Works fine one added.

**Comment by yourjelly** [comment]
It should be covered by the environment.yaml

https://github.com/hlky/stable-diffusion/blob/d4fc920b1e67abdcdb2d9ca95ce2890e849752d3/environment.yaml#L31

Does it really need to be run in the Dockerfile?

**Comment by bluedevil678** [comment]
Indeed it could be covered there, just provide one possible option ;)

**Comment by oc013** [comment]
It already updates on its own, just restart the container...
```
$ docker compose up
[+] Running 1/0
 ⠿ Container sd  Created                                                                                                                                             0.0s
Attaching to sd
sd  | Updating conda env: ldm ...
```
