### ISSUE TITLE
--optimized-turbo not working anymore?

### ISSUE THREAD

**Issue by pinilpypinilpy** [hlky/stable-diffusion#134]
Name says it all, on colab free tier the system ram runs out and the process gets killed.

**Comment by pinilpypinilpy** [comment]
A fix seems to be changing 
`if not opt.optimized:
        model.cuda()
`
to
`model.cuda()`

on line 360 and 361

**Comment by hlky** [comment]
Yes that was supposed to be for OOM optimized users but apparently it doesn't work, I can only go off what users report I dont have a 4gb vram card, sorry. The commit with that change has been reverted.
