### ISSUE TITLE
Negative Classifier Free Guidance Scale

### ISSUE THREAD

**Issue by slashedstar** [hlky/stable-diffusion#137]
Let the slider on the for Classifier Free Guidance Scale go to negative numbers, it works and yields very nice results by removing and substituting the things associated with the prompt.

An exemple:
![Untitled](https://user-images.githubusercontent.com/103432664/187476127-b1e1108a-aa41-4574-a774-e0f46151635d.png)

**Comment by hlky** [comment]
Done, minimum is now -40

my test sucks but i'm sure it can be used for awesome results!
![image](https://user-images.githubusercontent.com/106811348/187502442-a3b06336-5c90-4965-bfc6-4970ea0a2334.png)
