### ISSUE TITLE
Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by fabwa** [hlky/stable-diffusion#166]
Getting this for any image or setting i try on GFPGAN

**Comment by hlky** [comment]
you need the facexlib change that was made in the environment.yaml yesterday, update

**Comment by fabwa** [comment]
I pulled today and have facexlib==0.2.5.
Same issue tho.

RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
