### ISSUE TITLE
[BUG] facexlib version conflict with gfpgan

### ISSUE THREAD

**Issue by AscendedGravity** [hlky/stable-diffusion#168]
The repo located here: https://github.com/hlky/facexlib is on version 0.2.4 and the latest gfpgan has a dependency requirement of 0.2.5.

The following error occurs when trying to build environment:

> INFO: pip is looking at multiple versions of facexlib to determine which version is compatible with other requirements. This could take a while.
> INFO: pip is looking at multiple versions of clip to determine which version is compatible with other requirements. This could take a while.
> 
> The conflict is caused by:
>     The user requested facexlib 0.2.4 (from git+https://github.com/hlky/facexlib#egg=facexlib)
>     gfpgan 1.3.4 depends on facexlib>=0.2.5

**Comment by timbennett** [comment]
I got the same issue attempting to build the docker repo in https://github.com/AbdBarho/stable-diffusion-webui-docker

**Comment by DominikMa** [comment]
I replaced the line https://github.com/hlky/stable-diffusion/blob/fa977b3d6f9d0b264035c949fd70415476f00036/environment.yaml#L36 with
```- -e git+https://github.com/TencentARC/GFPGAN@v1.3.4#egg=GFPGAN```
to fix the installed version to tag 1.3.4

**Comment by hlky** [comment]
@DominikMa don't do this >_>

it's fixed now, gfpgan updated their requirements to facexlib 0.2.5, we forked facexlib to add a fix for gfpgan, I've pulled the changes from facexlib so everything is fine

**Comment by hlky** [comment]
Note you won't need to pull any changes, just run webui.cmd again
