### ISSUE TITLE
ModuleNotFoundError: No module named 'frontend' after running docker-compose up

### ISSUE THREAD

**Issue by timpal0l** [hlky/stable-diffusion#170]
```
sd                  | ModuleNotFoundError: No module named 'frontend'
sd                  | entrypoint.sh: Process is ending. Relaunching in 0.5s...
sd                  | entrypoint.sh: Launching...
sd                  | Relaunch count: 183
sd                  | Traceback (most recent call last):
sd                  |   File "scripts/webui.py", line 3, in <module>
sd                  |     from frontend.frontend import draw_gradio_ui
sd                  | ModuleNotFoundError: No module named 'frontend'
sd                  | entrypoint.sh: Process is ending. Relaunching in 0.5s...
```

after running the `docker-compose up` command I get stuck in a loop about it not being able to find the frontend module. How can I resolve this?

**Comment by hlky** [comment]
Possibly related #168 #169 #163 and fixed
Or it could be installation/docker issue 
Pull changes try again, reopen if there's still an issue

**Comment by timpal0l** [comment]
@hlky i have a fresh pull of the repo, and the latest docker on ubuntu 22. I have only run the the docker-compose up, is there anything else that is required?

**Comment by hlky** [comment]
Docker related issue then I believe, someone else provided the Dockerfile, I guess I should re do it or just figure out what the issue is so I'll have to install Docker

Can you try [this ](https://github.com/hlky/stable-diffusion/issues/129#issuecomment-1232214509)

Shouldn't be required and if that fixes it then it must be an issue with the docker setup

**Comment by rbracco** [comment]
I am also having this issue with both the docker script and the linux install script as in #129. I have the `No module named frontend`, and once I do the sys.path hack (usually this is a symptom of the repo itself not being installed properly as an editable install with `pip install -e .`) I get `ModuleNotFoundError: No module named gradio`
