### ISSUE TITLE
Two repositories makes it harder to look at diffs and view changes.

### ISSUE THREAD

**Issue by muchcharles** [hlky/stable-diffusion#193]
Could it make sense to use a development branch instead of the separate webui repository? Two repositories makes it harder to look at diffs and use git tools for searching changelogs, blaming files etc.

**Comment by JoshuaKimsey** [comment]
Well, the main point of having the two repos is that one is the stable branch containing the full Stable Diffusion code and the WebUI code, pulled over at specific periods when things are known to be working. The other repo is just for the WebUI code development primarily. 

It could be done in one repo, with multiple branches. But, that would make it harder for people to separate out what issues they have, Sd itself vs the WebUI code for example. It's possible once the project reaches a true Release point that the two could be merged and start using different branches. But that will be up to hlky and the others to decide that.

**Comment by rinukkusu** [comment]
@JoshuaKimsey I understand where you're coming from, but since the whole development mostly is done in the webui parts anyway, I don't see that much of a profit having two repos. 

Just go back the last 7 days of commits - it's 95% syncing files from the webui repo 😺

**Comment by rinukkusu** [comment]
Heh, okay
