### ISSUE TITLE
Resize mode in img2img : tensor size error

### ISSUE THREAD

**Issue by Guizmus** [hlky/stable-diffusion#200]
Using the webUI, in the img2img module, I get systematic tensor size error in a runtime error if the init picture needs resizing. not the same error as #147 displays so I put this in another issue.

Here is an init image and prompt that do keep generating the error, as well as a screenshot of the error.
![unknown](https://user-images.githubusercontent.com/1162494/187876033-d4792a95-ab0a-4c20-8eca-0322c9f33271.png)
A tropical island, screenshot from Curse of Monkey Island Game, Lucas Arts, Monkey island, digital artwork, ultra detailed

![image](https://user-images.githubusercontent.com/1162494/187876181-6d481a0d-409d-49d4-a573-98403fd59ba1.png)

I doubt this would change a lot since the error seems to happen before, but the error appeared on mutiple random seeds, I was using k_euler_a, with defaults webUI settings, to be complete

**Comment by adamesko** [comment]
I got the same thing - it turns out that you have to set the same resolution as in the source file. It is often not possible to set the exact resolution of the image in the settings so basically you have to prepare your file to match the resolutions that can be set in webui.

**Comment by Guizmus** [comment]
I tried the proposed fix, and it works, at least in the proposed test case. I'll report on #398 too

**Comment by hlky** [comment]
Pushed major txt2img ui overhaul that has img2img working in my tests
Please update and open a new issue if the problem recurs

**Comment by Angelore** [comment]
RuntimeError: The size of tensor a (128) must match the size of tensor b (96) at non-singleton dimension 3
It's borked again, sir.

**Comment by vdruts** [comment]
I'm also having this issue now.

**Comment by Guizmus** [comment]
I tested right now after the last commit (fbf814ebdff6ab08a56b87de947193e602a7918a)

The issue has evolved but is still blocking, I'll open a new issue detailing
