### ISSUE TITLE
k_euler very slow suddenly

### ISSUE THREAD

**Issue by 1blackbar** [hlky/stable-diffusion#213]
With k_euler_a i had like 6 seconds with 20 steps on 512x512, now in new version i have like 23 seconds (!!!!!!)
What happened ? Did something major was changed?

**Comment by hlky** [comment]
Nothing changed that would cause a decrease in speed. The speed can vary depending on the current activity of your computer.

If you can point out a commit where you think the speed was faster and a commit where you think the speed is slower I can investigate.
