### ISSUE TITLE
Newest release broke webui IMG2IMG

### ISSUE THREAD

**Issue by github-istrash** [hlky/stable-diffusion#215]
Previous release worked, now this is all I get every time I use img2img.  txt2image still works.

![image](https://user-images.githubusercontent.com/112638121/187933174-d3019763-254c-41de-b3a7-988030492213.png)

**Comment by altryne** [comment]
Please identify the commit that broke for you? 🙏 
Newest release is hard to pinpoint when there are so many collaborators
