### ISSUE TITLE
unsupported operand type(s) for +=: 'dict' and 'str'

### ISSUE THREAD

**Issue by orionflame** [hlky/stable-diffusion#221]
Hi,

I just installed the latest version and I tried face fix and upres modules they work fine. But when I tried to use a prompt to generate an image, it throws that error.

Here is the full stack error:
https://imgur.com/a/iIhPZpJ

**Comment by jim-22** [comment]
The problem is in this bit:

https://github.com/hlky/stable-diffusion/blob/e2897e6b17579b499578d2e88f6337025adaae08/scripts/webui.py#L987-L998

`info` was changed from a string to a dict but last two lines weren't updated to reflect that change.

**Comment by orionflame** [comment]
I just tried it same error.

**Comment by jim-22** [comment]
It works for me. Did you restart the python process and reload the window? It needs to reload the code.

**Comment by orionflame** [comment]
thx i was just retrying without doing that and i saw the updated code in the error thats why i thought it reloaded it. how can I restart the python process? you mean do the whole webui startup from anaconda again?

**Comment by James-Whitney** [comment]
can confirm it works after (requires restarting the webui.cmd)

**Comment by hlky** [comment]
Fixed, thanks @jim-22
