### ISSUE TITLE
Launch() Share=true location

### ISSUE THREAD

**Issue by Tom-the-moose** [hlky/stable-diffusion#23]
Hello, in previous versions there was a Launch() at the bottom of the webgui script. Where would we put it now? I attempted to put it in the only Launch() that was tied to the relaunch script and it errored out.

**Comment by hlky** [comment]
same place, ctrl+f demo.launch in webui.py

also please note: development of the webui takes places here [hlky/stable-diffusion-webui](https://github.com/hlky/stable-diffusion-webui)

create issues regarding webui.py there in the future please
