### ISSUE TITLE
cant complete a new fresh install 

### ISSUE THREAD

**Issue by kharshur** [hlky/stable-diffusion#39]
just deleted the stable diffusion main folder and deleted the lately created env (ldm and ldo) with miniconda

tried a new install fresh from the start. tried both webuildm and webui ; tried name "ldm" and "ldo" for env

 but it gets stuck

(it worked fine 2-3 days ago)

""each time i get :

Installing pip dependencies: - Ran pip subprocess with arguments:
['C:\\Users\\11\\.conda\\envs\\ldm\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\stable-diffusion-main\\condaenv.vu0qb86m.requirements.txt']
Pip subprocess output:
Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers#egg=taming-transformers (from -r C:\stable-diffusion-main\condaenv.vu0qb86m.requirements.txt (line 21))
  Cloning https://github.com/CompVis/taming-transformers to c:\stable-diffusion-main\src\taming-transformers

Pip subprocess error:
ERROR: Command errored out with exit status 128: git clone -q https://github.com/CompVis/taming-transformers 'C:\stable-diffusion-main\src\taming-transformers' Check the logs for full command output.

failed

CondaEnvException: Pip failed

""and after that : 

Traceback (most recent call last):
  File "scripts/webui.py", line 31, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...

**Comment by hlky** [comment]
Problem on your end, not my problem, follow the instructions

**Comment by Tuba202** [comment]
Did you ever fix this? I'm stuck with the same problem...

**Comment by hlky** [comment]
Problem on your end, not my problem, follow the instructions

**Comment by AndrWeisR** [comment]
I was getting those errors until I fixed the paths to my Anaconda installation in webuildm.cmd.

**Comment by kharshur** [comment]
> 

i noticed i did download and install Git recently, , so i un-isntalled Git, deleted all environments, updated my anaconda and it worked again

hope it helps

**Comment by Tuba202** [comment]
Ok, I figured out a fix after re-reading the instructions!
Change LDM to LDO in the environment file. Then re-run webiu.bat, and let it run. Even if it comes up with errors, just wait a while. I left my computer for 5 or so minutes, and I came back to it working PERFECTLY!
Hope this works for everyone else!

-Elliot

**Comment by Rademenes16** [comment]
I can't run webiu.bat because it's closing instantly. I renamed my environment

**Comment by paulroeppenack** [comment]
> I can't run webiu.bat because it's closing instantly. I renamed my environment

I have the same issue after 2 fresh installs. Anyone an idea what I'm doing wrong?

**Comment by Rademenes16** [comment]
# update

I fixed my issue by **dragging webui.cmd into command prompt** instead of directly opening it.

I saw someone doing it on yt video, I did the same and it worked. Hope it helps.
