### ISSUE TITLE
Create src/realesrgan/experiments/pretrained_models/ with environment - Running webui.cmd doesn't generate Realesrgan necessary folders

### ISSUE THREAD

**Issue by grexzen** [hlky/stable-diffusion#41]
Thanks for your guide and repo, it worked easily.

**Issue**: scr folder has gfpgan (/src/gfpgan/experiments/pretrained_models/), but not realesrgan (/src/realesrgan/experiments/pretrained_models) folders to place RealESRGAN_x4plus.pth and RealESRGAN_x4plus_anime_6B.pth

**Q**: what is full precision? 

Thanks!

**Comment by hlky** [comment]
> experiments/pretrained_models

You can make it yourself for now, there will be a fully automated powershell script at some point

> what is full precision?

Uses more vram for debatable differences or is required for some users with 16xx cards it seems

**Comment by hlky** [comment]
These folders should already be made on first run of webui.cmd it seems

**Comment by grexzen** [comment]
Is there a way to re-run setup again. Not sure why mine did not set the folders up, and I tried just adding those folders, but that did not work either. Thanks!
