### ISSUE TITLE
your bs broke my chcp

### ISSUE THREAD

**Issue by Parfolomew** [hlky/stable-diffusion#46]
delete this whole github until you can figure out how to make a program that doesn't change paths, delete github and ruin entire systems for the unexperienced. thanks for the coming hours of troubleshooting

**Comment by hlky** [comment]
It doesn't do anything like that, I don't know what chcp is, but this repo hasn't broken it.

**Comment by Parfolomew** [comment]
garbage.

**Comment by SunDevilJho** [comment]
I had to use windows 10’s control panel’s advanced system settings -> environment variables and add %SystemRoot%\system32 and %SystemRoot%\System32\Wbem.   This happened before I started using this repo for stable diffusion, I’m guessing it’s a bug in Anaconda or some other weird SW you used to setup SD.
