### ISSUE TITLE
Readme suggestion

### ISSUE THREAD

**Issue by vasimr** [hlky/stable-diffusion#50]
A few suggestions for the quick install steps that may make them more accessible to a less technical user:
1) add the link to download miniconda3 if possible
2) explicitly mention the ip-address / port to connect to once the server is running
3) clearly state how to relaunch the server. I know it's in the text, but it's a bit hidden. Perhaps a new heading about running it after install
4) explicitly mention how to quit the server

**Comment by Vyviel** [comment]
Maybe adding a section how to upgrade to the newest version might be useful for some people too

**Comment by bolognaflapjack** [comment]
where do I find the "model checkpoint", I've located miniconda, but not sure which model we're referring to.

**Comment by vasimr** [comment]
Adding a link to the model checkpoint is also a god idea. So perhaps 
1a. Add a link to the official model page (I'm not exactly sure what the github link guidelines are)

@bolognaflapjack You can find the model by searching for "CompVis/stable-diffusion-v-1-4-original", which will be on the 
huggingface website. You will need to create an account, accept the license, and then find the .cpk checkpoint file under "Files and Versions".

**Comment by hlky** [comment]
Feel free to pr any of these changes, keep checking wiki, there are plans to document everything, any help with documenting features will be appreciated
