### ISSUE TITLE
NameError: name 'goBig_strength' is not defined

### ISSUE THREAD

**Issue by Appolonius001** [hlky/stable-diffusion#52]
redid every install and still getting this error. updated from 20m ago.
did not install the developer extras

**Comment by hlky** [comment]
The implementation broke things, feature was removed for now,  keep checking wiki, it's being updated with planned new features including GoBIG and other upscalers

**Comment by HugoKlepsch** [comment]
You have to install the "ESRGAN and GFPGAN SUPPORT" from the wiki: https://rentry.org/GUItard


GFPGAN (Face Correction)
    1. Run webui.cmd at least once to generate the necessary folders
    2. Download the [GFPGAN pre-trained model](https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth)
    place it in /src/gfpgan/experiments/pretrained_models/
    3. Run webui.cmd and GFPGAN options should be available!
    ESRGAN (Upscaling)
    1. Run webui.cmd at least once to generate the necessary folders
    2. Download [RealESRGAN_x4plus.pth](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth) and [RealESRGAN_x4plus_anime_6B.pth](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth)
    place them in /src/realesrgan/experiments/pretrained_models
    3. Run webui.cmd and ESRGAN options should be available!

**Comment by hlky** [comment]
@HugoKlepsch 
>The implementation broke things, feature was removed for now, keep checking wiki, it's being updated with planned new features including GoBIG and other upscalers

https://github.com/hlky/stable-diffusion-webui/wiki/Upscalers
