### ISSUE TITLE
ValueError whenever using a k_ sampler with img2img

### ISSUE THREAD

**Issue by elihalpern** [hlky/stable-diffusion#57]
I get this error wheenver running img2img with any sampler but DDIM

> 
> File "scripts/webui.py", line 1188, in img2img
>     output_images, seed, info, stats = process_images(
>   File "scripts/webui.py", line 757, in process_images
>     samples_ddim = func_sample(init_data=init_data, x=x, conditioning=c, unconditional_conditioning=uc, sampler_name=sampler_name)
>   File "scripts/webui.py", line 1112, in sample
>     samples_ddim, _ = K.sampling.__dict__[f'sample_{sampler.get_sampler_name()}'](model_wrap_cfg, xi, sigma_sched, extra_args={'cond': conditioning, 'uncond': unconditional_conditioning, 'cond_scale': cfg_scale}, disable=False)
> ValueError: not enough values to unpack (expected 2, got 1)
>

**Comment by hlky** [comment]
Should be fixed, update

**Comment by elihalpern** [comment]
Thanks, fixed on my end as well!
