### ISSUE TITLE
gradio share url does not work, only on localhost

### ISSUE THREAD

**Issue by light-ikagi** [hlky/stable-diffusion#65]
Title. Adding `share=True` at
`self.demo.launch(show_error=True, server_name='0.0.0.0', share=True)`
works as expected, you get a shareable public link, however, it does not actually work. It shows the web UI, but that is about it. Generation functionality is lost, aka the backend. Localhost, however, works flawlessly.

Unfortunately, I couldn't find the solution myself, so I'll leave this here as an issue.

**Comment by hlky** [comment]
Known Gradio issue with share=True and gradio Blocks based interface

Not something that can be fixed without fixing Gradio itself

You can try a workaround way you would make anything accessible over the internet - port forwarding, dyndns or your own domain, and a reverse proxy. However remote internet based access is not a directly supported feature and just an artefact of using gradio, and as you can see, it doesn't work anyway

`server_name='0.0.0.0'` it's exposed on all interfaces so should be accessible on your local network disregarding any firewall issues you may have, however again it's not directly supported as you will need a workaround to access the files directly, although you could save them directly from the webui too

**Comment by parsec501** [comment]
> You can try a workaround way you would make anything accessible over the internet - port forwarding, dyndns or your own domain, and a reverse proxy

Should be noted though that exposing a personal device to the internet like this isn't the greatest of ideas unless one knows what is going on @light-ikagi
