### ISSUE TITLE
output not returned after about 1 minute on Colab

### ISSUE THREAD

**Issue by XmYx** [hlky/stable-diffusion#83]
Hi,
When running longer jobs, matrix's, output is saved but not returned to gr.Gallery, regardless of progressbar settings.
Would you be able to look into it in the notebook?

https://colab.research.google.com/drive/1cd35l21ewU0fwWEnPjY_th5YORmMfZCd

Tried with gradio 3.1.4  - 3.1.8b3

**Comment by hlky** [comment]
I don't make that colab, sorry, I don't know who does either, it probably needs to pull updates or something
