### ISSUE TITLE
Add colab button to Readme and Installation in wiki

### ISSUE THREAD

**Issue by altryne** [hlky/stable-diffusion#89]
@hlky I finally done did it! 

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/altryne/sd-webui-colab/blob/main/Stable_Diffusion_WebUi_Altryne.ipynb)

Runs beautifully 

The repo for the colab with instructions is here: 
https://github.com/altryne/sd-webui-colab

**Comment by hlky** [comment]
Thanks!
